name: CI - Backend ImovelMaps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: imovelmaps_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: imovelmaps_test
      DB_HOST: localhost
      DB_PORT: 5432
      NODE_ENV: test
      JWT_SECRET: testsecret

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar migrations e seeders
        run: |
          npx sequelize-cli db:migrate
          npx sequelize-cli db:seed:all

      - name: Rodar testes
        run: npm test
